Allow user to not set associated_redirect value
johngodley/redirection pull request #3585
Opened 2023-03-23 20:52 UTC by thunderdw

This PR addresses #3541.

Right now, if the user tries to remove the value from the `associated_redirect` field in the URL Monitor Changes section of the plugin options, the value is set to a trailing slash on save. As a result, when a user triggers the URL monitor by changing a post slug, two redirect entries are created.

[This commit](https://github.com/johngodley/redirection/commit/2d89b4702fb2d86420321616f4de135d74ca30b3#diff-03f15b1fc2b15d80272040930cb996e076590b464bb42687726aed7199be8e29L119-R121) that landed in version 5.3.7 removed the logic that only passed the `associated_redirect` value through `Red_Item_Sanitize::sanitize_url()` if the value had at least one character. Since `Red_Item_Sanitize::sanitize_url()` ensures the value starts with a trailing slash, the slash is added to the empty value.

This PR restores that logic, allowing the user to leave the `associated_redirect` field empty.

2023-03-28 16:43 UTC, robertstaddon requested changes
There's a typo on Line 120 of your code. You have two equals signs "==" instead of one "=". After making this change, your pull request worked great for me!

2023-03-28 16:46 UTC, thunderdw commented
> There's a typo on Line 120 of your code. You have two equals signs "==" instead of one "=". After making this change, your pull request worked great for me!

Thanks for the catch! Updated the PR

2023-03-28 16:51 UTC, robertstaddon commented
Thank you! Your new PR solved the issue for me!

2023-03-29 06:41 UTC, kage690 commented
Thank you all!

2023-04-02 06:46 UTC, merged